name: inventory_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  two_dimensional_scrollables: ^0.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobile_scanner: ^3.5.7  # バーコードスキャナー
  mysql1: ^0.19.0  # MySQL接続用
  http: ^0.13.4 #http通信用

flutter:
  uses-material-design: true

