// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3dztCKa3ISbuVYit6Ow56HdoD-5xHbfA',
    appId: '1:610021995720:web:0456df5a301bea0a17a1fd',
    messagingSenderId: '610021995720',
    projectId: 'employment-work-firebase-2b2f0',
    authDomain: 'employment-work-firebase-2b2f0.firebaseapp.com',
    storageBucket: 'employment-work-firebase-2b2f0.firebasestorage.app',
    measurementId: 'G-4CWB4QRNSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOTNv6TBkxU4vk8siJmSlICXGIdgDGUzY',
    appId: '1:610021995720:android:e822c9721ef4202d17a1fd',
    messagingSenderId: '610021995720',
    projectId: 'employment-work-firebase-2b2f0',
    storageBucket: 'employment-work-firebase-2b2f0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3dztCKa3ISbuVYit6Ow56HdoD-5xHbfA',
    appId: '1:610021995720:web:641193a109f6d41f17a1fd',
    messagingSenderId: '610021995720',
    projectId: 'employment-work-firebase-2b2f0',
    authDomain: 'employment-work-firebase-2b2f0.firebaseapp.com',
    storageBucket: 'employment-work-firebase-2b2f0.firebasestorage.app',
    measurementId: 'G-XPFMZWF2MG',
  );

}